#!/bin/bash

set -e

#####################
# --- Constants --- #
#####################

# Directory where this script is located (api_layer/)
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
# Root directory (parent of api_layer/)
ROOT_DIR="$( cd "$THIS_DIR/.." && pwd )"
MINIMUM_TEST_COVERAGE_PERCENT=0


##########################
# --- Task Functions --- #
##########################

# install core and development Python dependencies into the currently activated venv
function install {
    python -m pip install --upgrade pip
    # Install from root pyproject.toml with dev extras
    python -m pip install --editable "$ROOT_DIR/[dev]"
}

function run {
    # Clear any processes using port 8000 (uvicorn default port)
    echo "Checking for processes on port 8000..."
    if command -v lsof >/dev/null 2>&1; then
        # Kill processes using port 8000
        lsof -ti :8000 2>/dev/null | xargs kill -9 2>/dev/null && echo "✓ Cleared port 8000" || echo "Port 8000 is free"
    fi

    # Also kill any existing uvicorn processes
    if command -v pkill >/dev/null 2>&1; then
        pkill -f "uvicorn.*main:create_app" 2>/dev/null && echo "✓ Cleared existing uvicorn processes" || true
    fi

    # Small delay to ensure ports are released
    sleep 1

    # Add src to PYTHONPATH for imports
    export PYTHONPATH="$THIS_DIR/src:$PYTHONPATH"
    dltshr_workspace_url="https://adb-2329622552520735.15.azuredatabricks.net/" \
        uvicorn 'dbrx_api.main:create_app' --reload --factory
}


# run linting, formatting, and other static code quality tools
function lint {
    cd "$ROOT_DIR"
    SKIP=no-commit-to-branch pre-commit run --all-files
    cd "$THIS_DIR"
}

# same as `lint` but with any special considerations for CI
function lint:ci {
    cd "$ROOT_DIR"
    # We skip no-commit-to-branch since that blocks commits to `main`.
    # All merged PRs are commits to `main` so this must be disabled.
    SKIP=no-commit-to-branch pre-commit run --all-files
    cd "$THIS_DIR"
}

# execute tests that are not marked as `slow`
function test:quick {
    run-tests -m "not slow" ${@:-"$THIS_DIR/tests/"}
}

# execute tests against the installed package; assumes the wheel is already installed
function test:ci {
    INSTALLED_PKG_DIR="$(python -c 'import dbrx_api; print(dbrx_api.__path__[0])')"
    # in CI, we must calculate the coverage for the installed package, not the src/ folder
    COVERAGE_DIR="$INSTALLED_PKG_DIR" run-tests
}

# (example) ./run.sh test tests/test_states_info.py::test__slow_add
function run-tests {
    PYTEST_EXIT_STATUS=0

    # clean the test-reports dir
    rm -rf "$THIS_DIR/test-reports" || mkdir "$THIS_DIR/test-reports"

    # Add src to PYTHONPATH for imports
    export PYTHONPATH="$THIS_DIR/src:$PYTHONPATH"

    # execute the tests from root dir (where pyproject.toml is)
    cd "$ROOT_DIR"
    python -m pytest ${@:-"$THIS_DIR/tests/"} \
        --cov "${COVERAGE_DIR:-$THIS_DIR/src}" \
        --cov-report html \
        --cov-report term \
        --cov-report xml \
        --junit-xml "$THIS_DIR/test-reports/report.xml" \
        --cov-fail-under "$MINIMUM_TEST_COVERAGE_PERCENT" || ((PYTEST_EXIT_STATUS+=$?))

    # Move coverage reports to api_layer
    mv coverage.xml "$THIS_DIR/test-reports/" 2>/dev/null || true
    mv htmlcov "$THIS_DIR/test-reports/" 2>/dev/null || true
    mv .coverage "$THIS_DIR/test-reports/" 2>/dev/null || true

    cd "$THIS_DIR"
    return $PYTEST_EXIT_STATUS
}

function test:wheel-locally {
    deactivate || true
    rm -rf test-env || true
    python -m venv test-env
    source test-env/bin/activate
    clean || true
    pip install build
    build
    # Install wheel with dev extras to get all test dependencies
    pip install "$ROOT_DIR/dist/*.whl[dev]"
    test:ci
    deactivate || true
}

# serve the html test coverage report on localhost:8000
function serve-coverage-report {
    python -m http.server --directory "$THIS_DIR/test-reports/htmlcov/" 8000
}

# build a wheel and sdist from the Python source code
function build {
    cd "$ROOT_DIR"
    python -m build --sdist --wheel "$ROOT_DIR/"
    cd "$THIS_DIR"
}

function release:test {
    lint
    clean
    build
    publish:test
}

function release:prod {
    release:test
    publish:prod
}

function publish:test {
    try-load-dotenv || true
    twine upload "$ROOT_DIR/dist/*" \
        --repository testpypi \
        --username=__token__ \
        --password="$TEST_PYPI_TOKEN"
}

function publish:prod {
    try-load-dotenv || true
    twine upload "$ROOT_DIR/dist/*" \
        --repository pypi \
        --username=__token__ \
        --password="$PROD_PYPI_TOKEN"
}

# remove all files generated by tests, builds, or operating this codebase
function clean {
    echo "Cleaning build artifacts..."
    rm -rf "$ROOT_DIR/dist" "$ROOT_DIR/build" "$THIS_DIR/test-reports" "$THIS_DIR/htmlcov"
    rm -f "$ROOT_DIR/coverage.xml" "$THIS_DIR/coverage.xml" "$ROOT_DIR/.coverage" "$THIS_DIR/.coverage"

    echo "Cleaning Python cache files..."
    find "$ROOT_DIR" \
      -type d \
      \( \
        -name "__pycache__" \
        -o -name ".pytest_cache" \
        -o -name ".mypy_cache" \
        -o -name "*.dist-info" \
        -o -name "*.egg-info" \
        -o -name "*htmlcov" \
      \) \
      -not -path "*env/*" \
      -not -path "*venv/*" \
      -exec rm -rf {} + 2>/dev/null || true

    echo "Cleaning .pyc files..."
    find "$ROOT_DIR" \
      -type f \
      -name "*.pyc" \
      -not -path "*env/*" \
      -not -path "*venv/*" \
      -exec rm -f {} + 2>/dev/null || true

    echo "Cleaning MagicMock test artifacts..."
    find "$ROOT_DIR" \
      -type f \
      -name "*MagicMock*" \
      -not -path "*env/*" \
      -not -path "*venv/*" \
      -exec rm -f {} + 2>/dev/null || true

    echo "✓ Cleanup complete!"
}

# export the contents of .env as environment variables
function try-load-dotenv {
    # Try api_layer/.env first, then root/.env
    if [ -f "$THIS_DIR/.env" ]; then
        while read -r line; do
            export "$line"
        done < <(grep -v '^#' "$THIS_DIR/.env" | grep -v '^$')
    elif [ -f "$ROOT_DIR/.env" ]; then
        while read -r line; do
            export "$line"
        done < <(grep -v '^#' "$ROOT_DIR/.env" | grep -v '^$')
    else
        echo "no .env file found"
        return 1
    fi
}

# generate OpenAPI JSON specification for Azure APIM compatibility
function generate-openapi {
    local env="${1:-dev}"
    local output="${2:-apim_openapi/openapi.json}"

    echo "🔄 Generating OpenAPI spec for environment: $env"

    # Validate environment parameter
    case "$env" in
        dev|uat|prod)
            ;;
        *)
            echo "❌ Invalid environment: $env"
            echo "Valid environments: dev, uat, prod"
            return 1
            ;;
    esac

    # Add src to PYTHONPATH for imports
    export PYTHONPATH="$THIS_DIR/src:$PYTHONPATH"

    # Generate OpenAPI spec
    python "$THIS_DIR/scripts/generate_openapi.py" --env "$env" --output "$output" --pretty

    if [ -f "$output" ]; then
        echo "✅ OpenAPI spec generated successfully!"
        echo "📍 Output: $output"
        echo "🔧 Environment: $env"
        echo "📊 Ready for Azure APIM import"

        # Show file size if available
        if command -v du >/dev/null 2>&1; then
            local file_size
            file_size=$(du -h "$output" 2>/dev/null | cut -f1 || echo "unknown")
            echo "📏 File size: $file_size"
        fi

        # Count endpoints if jq is available
        if command -v jq >/dev/null 2>&1; then
            local endpoint_count
            endpoint_count=$(jq '.paths | length' "$output" 2>/dev/null || echo "unknown")
            echo "🌐 Endpoints: $endpoint_count"
        fi
    else
        echo "❌ Failed to generate OpenAPI spec"
        return 1
    fi
}

# generate OpenAPI for development environment
function generate-openapi:dev {
    generate-openapi "dev" "${1:-apim_openapi/openapi-dev.json}"
}

# generate OpenAPI for UAT environment
function generate-openapi:uat {
    generate-openapi "uat" "${1:-apim_openapi/openapi-uat.json}"
}

# generate OpenAPI for production environment
function generate-openapi:prod {
    generate-openapi "prod" "${1:-apim_openapi/openapi-prod.json}"
}

# generate OpenAPI for all environments
function generate-openapi:all {
    echo "🔄 Generating OpenAPI specs for all environments..."

    generate-openapi:dev "apim_openapi/openapi-dev.json"
    generate-openapi:uat "apim_openapi/openapi-uat.json"
    generate-openapi:prod "apim_openapi/openapi-prod.json"

    echo "✅ All OpenAPI specs generated successfully!"
    echo ""
    echo "Generated files:"
    echo "  📝 Development: apim_openapi/openapi-dev.json"
    echo "  📝 UAT:         apim_openapi/openapi-uat.json"
    echo "  📝 Production:  apim_openapi/openapi-prod.json"
}

# print all functions in this file
function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}
